spring:
  port : 8082
  datasource:
    url: jdbc:mysql://localhost/practica
    username: root
    password: ' ' 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect 